sudo: false

language: haskell

cache:
  directories:
    - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack setup --no-system-ghc #--no-terminal --skip-ghc-check
- stack build  --no-system-ghc #--no-terminal --skip-ghc-check --only-snapshot
