resolver: lts-14.12

packages:
  - '.'

extra-deps:
  - simple-affine-space-0.1
  - Yampa-0.11

flags: {}

extra-package-dbs: []

nix:
  enable: true
  pure: false # use exported environment variables
  packages: [freeglut]
